### ISSUE TITLE
Hi can you tell me how to give different  image dataset to model for checking the model performance.Because i didn't find a general preprocess template

### ISSUE THREAD

**Issue by gauravjain10** [deu30303/RUC#10]

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!
I used benchmark dataset like CIFAR-10.  Pytorch Library is used to load dataset.
I separate each dateset loader with individual file. (For example, CIFAR-10 : main_ruc_cifar10.py) 

Thank you again for your interest.
