### ISSUE TITLE
안녕하세요! 커스텀 데이터에서 사용하고 싶어 질문드립니다.

### ISSUE THREAD

**Issue by nobile98** [deu30303/RUC#2]
데이터set에 따라 main. py의 차이가 있는 것 같은데 어떤 차이가 있는지 질문 드립니다.

**Comment by deu30303** [comment]
안녕하세요. 저희 연구에 관심을 가져주셔서 감사합니다!
큰 차이는 없지만, 데이터 로더나 하이퍼파라미터가 조금씩 차이가 있습니다. 
하이퍼파라미터의 경우 아래의 아카이브를 참조하시면 됩니다. 
https://arxiv.org/abs/2012.11150
감사합니다.
