### ISSUE TITLE
和DividMix论文比较

### ISSUE THREAD

**Issue by lihuikenny** [deu30303/RUC#3]
粗看了一下代码和论文，似乎除了伪标签是通过匈牙利匹配算法生产之外，其他的和DividMix(代码也已开源)基本差不多，训练策略基本都一样，不知道作者如何解释，或许是本人研究不够深，还请作者指点迷津....

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

RUC introduces the robust learning concept to mitigate the memorization of noisy unsupervised clustering's pseudo label, which leads to substantial improvements in the calibration and clustering performance.  We adopt DivideMix framework as robust learning. However, we suggest several other strategy (ex, sampling strategy, label smoothing, strong augmentation) for better performance.

Thank you again for your interest.

**Comment by lihuikenny** [comment]
> Hi, thank you for your interest in our work!
> 
> RUC introduces the robust learning concept to mitigate the memorization of noisy unsupervised clustering's pseudo label, which leads to substantial improvements in the calibration and clustering performance. We adopt DivideMix framework as robust learning. However, we suggest several other strategy (ex, sampling strategy, label smoothing, strong augmentation) for better performance.
> 
> Thank you again for your interest.

非常感谢您的解答，还有个问题就是，Extract Pseudo Label【line328】过程中，net_uc和net_embd似乎没有训练过，只是加载了预训练模型，去获取P_label，从而得到devide数据；那么这岂不是很依赖与预训练模型的性能？刚好您没给出预训练模型，那是不是随机初始化的模型也可以并不影响最终结构，因为这两个网络结构都没有参与迭代训练。还请指点，谢谢！

**Comment by deu30303** [comment]
You should load the pretrained network from SCAN github because RUC is add-on module. net_uc is from SCAN clustering model and net_embed is from SimCLR pretrained model.  
Thank you.
