### ISSUE TITLE
Where should I get the pre-trained model for "o-model" and "e_model"?

### ISSUE THREAD

**Issue by ValkyriaLenneth** [deu30303/RUC#4]
Hi, I want to reproduce your code, however, I noticed that it is necessary to load pretrained model from param "o_model" and "e_model" which is absent in the repo neither readme.md. 
Where could I get them? Thanks a lot.

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

You can get pretrained-model  from SCAN GitHub.
https://github.com/wvangansbeke/Unsupervised-Classification
I am sorry for the inconvenience.

Thank you again for your interest.

**Comment by ValkyriaLenneth** [comment]
Thank you very much for the reply
