### ISSUE TITLE
About “ checkpoints ”

### ISSUE THREAD

**Issue by cwpl** [deu30303/RUC#5]
Excuse me, could you please provide the documents of selflabel_cifar-10.pth.tar and simclr_cifar-10.pth.tar ?

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

You can get pretrained-model from SCAN GitHub.
https://github.com/wvangansbeke/Unsupervised-Classification
selflabel_cifar-10.pth.tar is SCAN's pretrained model and simclr_cifar-10.pth.tar is SimClR pretrained model.

Thank you again for your interest.
