### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by zwhyOuO** [deu30303/RUC#7]
The scan github [https://github.com/wvangansbeke/Unsupervised-Classification](url) only support "SCAN-loss" and "Self-labeling" but not the SCAN's pretrained model and  SimClR pretrained model which you wrote in the other issue.There is no SimCIR at all.How can I correspond the pretrained model?

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

You can get pretrained-model from SCAN GitHub model zoo. 
SCAN GitHub  provides SimCLR pretrained model and SCAN's pretrained model (Self-labeling).
![image](https://user-images.githubusercontent.com/39057852/116503356-cd9a7000-a8f0-11eb-8792-ce98cce54307.png)


Thank you again for your interest.

**Comment by zwhyOuO** [comment]
I got it!Thank you for your reply!
