### ISSUE TITLE
original model  vs   embedding model 

### ISSUE THREAD

**Issue by DalalAlmutawa** [deu30303/RUC#8]
Hello
what different between  
  --o_model O_MODEL     original model path
  --e_model E_MODEL     embedding model path

Where do I find them?
There is only one model 
 
![Screenshot from 2021-06-02 12-45-40](https://user-images.githubusercontent.com/22529131/120459279-b7287e00-c3a0-11eb-839b-c0becbd7238e.png)

Thanks

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

I changed the github README.
Please Check README

Sorry for the delayed response.
